In [1]:
alias_url = {
    'Brazil'  : 'dados.gov.br',
    'Dominican Republic' : 'www.datos.gob.do',
}

In [2]:
#alias = 'Dominican Republic'
#query     = 'estudio'

In [3]:
alias = 'Brazil'
query = 'IBGE Censo'

In [4]:
hyperlink = 'https://'+alias_url[alias]

# Módulos e pacotes

## Instalação

In [5]:
!pip install unidecode

Requirement already satisfied: unidecode in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (1.3.2)

In [6]:
!pip install pymupdf

Requirement already satisfied: pymupdf in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (1.19.3)

In [7]:
!pip install lxml

Requirement already satisfied: lxml in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (4.6.5)

In [8]:
!pip install pandas

Requirement already satisfied: pandas in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from pandas) (1.21.4)
Requirement already satisfied: pytz>=2017.3 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

In [9]:
!pip install ipywidgets

Requirement already satisfied: ipywidgets in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (7.6.5)
Requirement already satisfied: ipython-genutils~=0.2.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets) (0.2.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets) (1.0.2)
Requirement already satisfied: ipython>=4.0.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets) (7.30.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets) (3.5.2)
Requirement already satisfied: nbformat>=4.2.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets) (5.1.3)
Requirement already satisfied: ipykernel>=4.5.1 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets) (5.5.5)
Requirement already satisfied: traitlets>=4.3.1 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets) (5.1.1)
Requirement already satisfied: tornado>=4.2 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets) (6.1)
Requirement already satisfied: jupyter-client in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets) (7.1.0)
Requirement already satisfied: pygments in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipython>=4.0.0->ipywidgets) (2.10.0)
Requirement already satisfied: decorator in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipython>=4.0.0->ipywidgets) (5.1.0)
Requirement already satisfied: pickleshare in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipython>=4.0.0->ipywidgets) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipython>=4.0.0->ipywidgets) (3.0.24)
Requirement already satisfied: pexpect>4.3 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipython>=4.0.0->ipywidgets) (4.8.0)
Requirement already satisfied: setuptools>=18.5 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipython>=4.0.0->ipywidgets) (58.0.4)
Requirement already satisfied: jedi>=0.16 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipython>=4.0.0->ipywidgets) (0.18.1)
Requirement already satisfied: backcall in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipython>=4.0.0->ipywidgets) (0.2.0)
Requirement already satisfied: matplotlib-inline in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from ipython>=4.0.0->ipywidgets) (0.1.3)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets) (0.8.3)
Requirement already satisfied: jupyter-core in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets) (4.9.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets) (4.2.1)
Requirement already satisfied: attrs>=17.4.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets) (21.2.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets) (0.18.0)
Requirement already satisfied: ptyprocess>=0.5 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets) (0.7.0)
Requirement already satisfied: wcwidth in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from widgetsnbextension~=3.5.0->ipywidgets) (6.4.6)
Requirement already satisfied: pyzmq>=17 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (19.0.2)
Requirement already satisfied: nest-asyncio>=1.5 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (1.5.4)
Requirement already satisfied: argon2-cffi in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (20.1.0)
Requirement already satisfied: jinja2 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (3.0.3)
Requirement already satisfied: terminado>=0.8.3 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.12.1)
Requirement already satisfied: nbconvert in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (6.3.0)
Requirement already satisfied: prometheus-client in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.12.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (1.8.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets) (2.8.2)
Requirement already satisfied: entrypoints in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets) (0.3)
Requirement already satisfied: six>=1.5 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from python-dateutil>=2.1->jupyter-client->ipykernel>=4.5.1->ipywidgets) (1.16.0)
Requirement already satisfied: cffi>=1.0.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (1.14.6)
Requirement already satisfied: pycparser in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (2.0.1)
Requirement already satisfied: jupyterlab-pygments in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.1.2)
Requirement already satisfied: bleach in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (4.1.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (1.5.0)
Requirement already satisfied: defusedxml in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.7.1)
Requirement already satisfied: testpath in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.8.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.5.9)
Requirement already satisfied: packaging in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (21.3)
Requirement already satisfied: webencodings in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.5.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/gois/miniconda3/envs/jlab/lib/python3.9/site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (3.0.6)

## Importação

In [11]:
import re
import fitz
import requests
import pandas

from unidecode import unidecode

from itertools import chain
from lxml.etree import HTML

import IPython
import ipywidgets
#import google.colab

# Funções

## auxiliares

#### lambdas

##### strip

In [12]:
strip_ = lambda T: set( t.strip() for t in T if t.strip() )
strip  = lambda T: '\n'.join( strip_( T ) ).strip()

##### plain

In [13]:
plain  = lambda I: list( chain.from_iterable( I ) )

## get_url_html

In [14]:
def get_url_html(url):
    requested         = requests.request('GET', url)
    html              = HTML(requested.text)    
    html.nsmap['url'] = url

    return html

## xpath

### contains_clause

In [15]:
def contains_clause(dic, operator='OR'):
    predicados = ["contains(@{k},'{v}')".format(k=k,v=v) for k,v in dic.items()]

    return operator.join(predicados)

### compose_xpath

In [16]:

def compose_xpath(element,attribute,content):
    dictionary = contains_clause({attribute:content})

    str_dict = {
        'element' : element,
        'dictionary' : dictionary 
    }

    return "{element}[{dictionary}]".format(**str_dict)

### get_xnodes

In [17]:

def get_xnodes(html, element, attribute='class', content='', complement=''):
    if complement:
        xnode = html.xpath(compose_xpath(element,attribute,content) + complement)
    else:
        xnode = html.xpath(compose_xpath(element,attribute,content) )
    return xnode if xnode else None

### get_xnode

In [18]:

def get_xnode(html, element, attribute='class', content='', complement=''):
    xnodes = get_xnodes(html, element, attribute, content, complement)
    return xnodes[0] if xnodes else None

## datasets

### get_html_page_count

In [19]:
 
def get_html_page_count(html):
    xnode = get_xnode( html, '//div', 'class', 'pagination' ) 
    
    if xnode is None:
        return 1
    
    pdiv = xnode.xpath( '//li/a/text()' )
    
    def pmax(pdiv):
        V = [1]
        for p in pdiv:
            try:
                v = int(p)
                V.append(v)       
            except:
                continue
        return max(V)    
    return pmax(pdiv)

### get_query_page_count

In [20]:

def get_query_page_count(hyperlink,query):
    html = get_url_html( hyperlink + '/dataset?q=%s' % query)
    return get_html_page_count( html )

### get_html_items_href

In [21]:

def get_html_items_href(html):
    xnodes = get_xnodes( html, './/h3', 'class', 'dataset-heading' , '//a/@href' ) 
    return xnodes

### get_html_dataset

In [22]:

def get_html_dataset(html):    
    article_html = get_xnode(html , '//article')
    
    dataset = dict()
    
    dataset['organization'] = ' '.join(set([x.strip() for x in get_xnodes(html, './/div','class','module-content','//h1//text()')]))
    dataset['title']        = strip( get_xnodes( article_html , 'div/h1/text()') ) 
    dataset['key']          = re.sub('[^\w]','_',unidecode(dataset['title']).lower())
    z = get_xnodes(article_html,'//div','class','notes','//p/text()')
    dataset['text'] = strip(z) if z else ''
    dataset['url']          = get_xnodes( article_html, '//ol', 'class', 'breadcrumb', '//li/a/@href')

    return dataset

### get_html_dataset_license

In [23]:

def get_html_dataset_license(html,hyperlink='https://dados.gov.br'):
    xnode = get_xnode( html, '//section','class','license') 

    if not xnode: return dict(title='NA',href='',text='',logo='')

    license_title = xnode.xpath( './/@title' )
    license_href  = xnode.xpath( './/@href')
    license_text  = [ text.strip() for text in xnode.xpath( './/text()' ) if text.strip() ]
    license_logo  = [ hyperlink + p for p in xnode.xpath( './/img//@src' ) ]
    
    license_dict          = dict()
    license_dict['title'] = license_title
    license_dict['href']  = license_href
    license_dict['text']  = license_text
    license_dict['logo']  = license_logo

    return license_dict

### get_html_dataset_resources_href

In [24]:

def get_html_dataset_resources_href(html):
    return get_xnodes(html,'//a','class','heading','/@href')

### get_html_resource_info

In [25]:
def get_html_resource_info(html):
    
    ths     = get_xnodes( html, '//table', 'class', 'table-condensed','/tbody//th/text()')
    headers = [re.sub('[^\w]','_',unidecode(th.lower())) for th in ths]
    tds     = get_xnodes( html, '//table', 'class', 'table-condensed','/tbody//td')
    data    = [strip(get_xnodes(td, './/text()')).strip() for td in tds]

    content = get_xnode( html, '//div','class','module-content')


    info_dict        = {h:d for h,d in zip(headers,data)}
    info_dict['resource_url'] = str(get_xnode( html, '//a','class','resource-url-analytic','/@href'))
    
    info_dict['resource_title'] = str(get_xnode( content, './/h1', 'class', 'page-heading','//text()'))
    info_dict['resource_description'] = str(get_xnode( content, './/div', 'class', 'prose notes','//text()'))

    return info_dict

### auxiliares

#### \_\_dir_repr\_\_

In [26]:

def __dir_repr__(variable=dict,pattern=''):
    dir_type_dict = dict()
    
    for attribute in dir(variable):
        if not re.findall(pattern, attribute): continue
        value = getattr(variable,attribute)
        typename = type(value).__name__
        
        if typename not in dir_type_dict:
            dir_type_dict[typename] = [(attribute,value)]
        else:
            dir_type_dict[typename].append((attribute,value))
        
    for key, items in dir_type_dict.items():
        print(key)
        print()
        for attribute,value in items:
            print('\t',attribute)
        print()
        #print('{: <30s}{:<20s}'.format(typename, attribute))

#### show_url

In [27]:

def show_url( url='https://'+hyperlink ):
    dadosgov_frame = IPython.display.IFrame(src=url,width='100%',height='500px')
    display(dadosgov_frame)
    return

#### query_site

In [28]:

def query_site( query=''):
    query = query.lower()
    query = unidecode.unidecode(query)
    query = re.sub('[^a-z\s\'\"]','',query)
    query = re.sub('\s+','+',query)
    
    url = hyperlink='/dataset?q=%s' % query
    print(url)
    dadosgov_frame = IPython.display.IFrame(src=url,width='100%',height='500px')
    display(dadosgov_frame)
    return dadosgov_frame

#### lambdas

##### get_query_page_url

In [29]:
get_query_page_url   = lambda h, q, p : h + '/dataset' + '?q=' + q + ( ( '&page=' + str(p) ) if ( p > 1 ) else '' )

##### get_query_page_html

In [30]:
get_query_page_html  = lambda h, q, p : get_url_html( get_query_page_url( h, q, p ) )

##### get_query_page_items

In [31]:
get_query_page_items = lambda h, q, p : get_html_items_href( get_query_page_html( h, q, p ) )

##### get_query_items_href

In [32]:
get_query_items_href = lambda h, q    : plain([ get_query_page_items( h, q, p+1 ) for p in range( get_query_page_count( h, q ) ) ])

# Leitura

In [36]:
query   = re.sub('[^\w]',' ',unidecode(query))
query   = re.sub('\s+'  ,' ',query)
query   = re.sub('\s'   ,'+',query)

query = 'UFRN discentes'

In [37]:
query_url = get_query_page_url(hyperlink,query,1)

In [39]:
print(query_url)
show_url(query_url)

https://dados.gov.br/dataset?q=UFRN discentes

## visualização

In [40]:
resources = []

In [41]:
items_href = []
page_count = get_query_page_count( hyperlink , query )
page_count

1

In [42]:
for page in range( page_count ):
    print('page {page} of {page_count}'.format(page_count=page_count,page=page+1) )
    html = get_query_page_html( hyperlink, query, page+1 )
    html_items = get_html_items_href(html)
    tuple(map(lambda item: print('\t',hyperlink+item), html_items));
    items_href += html_items

page 1 of 1
	 https://dados.gov.br/dataset/discentes
	 https://dados.gov.br/dataset/dados-complementares-de-discentes
	 https://dados.gov.br/dataset/dados-socio-economicos-de-discentes

In [43]:
ih = 0
 
print(hyperlink + items_href[ih])
show_url(hyperlink + items_href[ih])

https://dados.gov.br/dataset/discentes

## arquivos

In [44]:
import time

In [45]:
import pandas
resources = []
for item_href in items_href:
    item_url = hyperlink + item_href
 
    print('\n\n\t', item_url, end='\n\n')
    dataset_html   = get_url_html( item_url )
 
    dataset        = get_html_dataset( dataset_html )
    license        = get_html_dataset_license ( dataset_html )
    resources_href = get_html_dataset_resources_href( dataset_html )
 
    for resource_href in resources_href:
        resource_url  = hyperlink + resource_href 
 
        resource_html = get_url_html( resource_url )  
        resource_dict = get_html_resource_info(resource_html)
 
        a = 'http://landpage-h.cgu.gov.br/dadosabertos/index.php?url='
        resource_dict['resource_url_out'] = resource_dict['resource_url'].replace(a,'') if resource_dict['resource_url'] else None        

        resource_dict.update({('dataset_'+k):v for k,v in dataset.items()})
        resource_dict.update({('license_'+k):v for k,v in license.items()})
 
        resource_dict['havested'] = time.ctime()
        
        print('\t\t',resource_dict['resource_url_out'], end='\n')
 
        resources.append( resource_dict )

	 https://dados.gov.br/dataset/discentes

<ipython-input-23-b0cbb787167f>:4: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not xnode: return dict(title='NA',href='',text='',logo='')

		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/a55aef81-e094-4267-8643-f283524e3dd7/download/discentes-2019.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/146b749b-b9d0-49b2-b114-ac6cc82a4051/download/discentes-2018.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/dc732572-a51a-4d4a-a39d-2db37cbe5382/download/discentes-2017.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/7d2fa5b3-743f-465f-8450-91719b34a002/download/discentes-2016.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/e2b5b843-4f58-497e-8979-44daf8df8f94/download/discentes-2015.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/6c23a430-9a7c-4d0f-9602-1d5d97d40e6a/download/discentes-2014.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/dba208c2-822f-4e26-adc3-b61d4cb110b6/download/discentes-2013.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/fc283aa9-61a7-4cf0-91fb-c403c0817b48/download/discentes-2012.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/2bb3dec9-7f23-434c-a179-21515f91abc8/download/discentes-2011.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/5fc61f78-19b4-4020-9f3c-c298cb8a63aa/download/discentes-2010.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/861b96a8-5304-4e6a-a8c4-068533ec7cb9/download/discentes-2009.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/b5144c99-81f3-4cfc-8938-18adb81ae3c0/download/discentesdicionario.pdf
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/7795c538-86fc-483f-9da9-67b2fcc834ae/download/discentes-2020.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/ba2e0a43-305f-4020-b6a7-9c125f766f63/download/discentes-2008.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/ed337a80-a0ba-4e69-b6f1-1493c51467ac/download/discentes-2002.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/3cfa42b7-315f-4d02-abe7-fb81a495be5a/download/discentes-2007.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/8bb0c8da-4221-4ade-abaa-2fe4b1f3502f/download/discentes-2006.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/e3d118c9-73c8-47fe-8264-3f077a8ad44d/download/discentes-2005.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/acdf58ab-c4fc-4199-a1a4-c58a39638ce7/download/discentes-2004.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/3c9cbd05-8e20-4211-a068-423bd314572c/download/discentes-2001.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/d6282624-a60b-4e97-af04-397f87c7a454/download/discentes-1998.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/166d8d15-72a5-45cf-aeb6-795e7d2e14dc/download/discentes-1996.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/018f6b0b-b788-4db0-99fc-0b0dc647d241/download/discentes-1995.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/cf451687-b7a5-413a-b044-0c99ad9ee55e/download/discentes-1992.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/ff37f985-cf9c-40f8-9ceb-201b22ebb8c6/download/discentes-1990.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/db542795-74c8-4d92-8986-ccc331da6adb/download/discentes-1991.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/ac2acdb3-02c0-4334-9865-d384eb2de3b6/download/discentes-2021.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/e467b303-fa5a-4759-b6d9-0fef03df3d5a/download/discentes-2003.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/da0093b5-fd23-4ab4-8420-e73fc8962c24/download/discentes-1999.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/cb089e24-357e-49f9-8afd-18af5b3e2301/download/discentes-1997.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/4a30217c-cc0f-4d0d-87c6-ee4a0aafd684/download/discentes-1994.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/3e4a3eef-02e7-44c6-929e-5f4a3f795382/download/discentes-1993.csv
		 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/2042b913-0ff8-4a3a-a7ca-c03a253a045e/download/discentes-2000.csv


	 https://dados.gov.br/dataset/dados-complementares-de-discentes

		 https://dados.ufrn.br/dataset/80b1a8e9-2e40-4c6c-97ea-d595a3c8b8f5/resource/0e287fe5-badb-4b34-b1bf-8815db5dfbeb/download/dados-pessoais-discentes.csv
		 https://dados.ufrn.br/dataset/80b1a8e9-2e40-4c6c-97ea-d595a3c8b8f5/resource/c49d5f58-41e4-4ec0-8774-cc0da45f149d/download/dicionario-de-dados---discentes-da-instituicao.pdf


	 https://dados.gov.br/dataset/dados-socio-economicos-de-discentes

		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/2b8de259-1674-4713-bbf5-167e644af5d9/download/dados-socioeconomicos-discentes-20191.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/333ba797-a810-4265-b189-2887d0f77dfe/download/dados-socioeconomicos-discentes-20182.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/365454a6-0f0e-4028-a418-ac20f18339f6/download/dados-socioeconomicos-discentes-20181.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/15353bfe-dbae-4b92-ba72-095dca8c086d/download/dados-socio-economicos-20172.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/07eb5987-63c4-4848-acc6-550e2390b405/download/dados-socioeconomicos-discentes-20171.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/bb3f78da-55a7-4b23-abdc-9de974dc1e31/download/dados-socioeconomicos-discentes-20162.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/2f195ce7-f01a-4b41-acbd-b6245ccf0145/download/dados-socioeconomicos-discentes-20161.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/c5e502e5-50b3-46be-8185-a1ce30415db5/download/dados-socioeconomicos-discentes-20152.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/ddb2a4d8-590f-4fd1-8edc-8238d855f47b/download/dados-socioeconomicos-discentes-20151.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/6a4c927a-150a-4630-b858-a32ec5c6495a/download/dados-socio-economicos-20142.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/c7204eb0-7202-423f-ae2e-d844fee66492/download/dados-socio-economicos-20141.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/67c56b36-b036-452c-af5d-f7aaa87fce47/download/dados-socio-economicos-20132.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/40831ad5-2e94-4110-8eba-bae4da1c9797/download/dados-socio-economicos-20131.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/3c2ae687-e541-40f0-9494-d005e89a1cb2/download/dados-socio-economicos-20122.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/7c5957ac-5146-438a-83ac-423c20bd4c57/download/dados-socio-economicos-20121.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/a54200ea-09fe-4ed5-8d31-44860608de2c/download/dados-socio-economicos-20112.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/7f819fb4-9a70-4bd7-8a7b-48182ba7ad72/download/dados-socio-economicos-20111.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/1ebaedfb-280a-4a14-a929-b96f2c0ea2c2/download/dados-socio-economicos-20102.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/f8e91076-eae7-41e5-8adf-2209e66966eb/download/dados-socio-economicos-discentes.pdf
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/a947133d-ad21-4907-af12-8f0a91135af4/download/dados-socio-economicos-discentes-2019.2.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/cf818b90-0867-4d2f-a5db-9c4707db34b7/download/dados-socio-economicos-discentes-2020.1.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/103ded7f-c045-4e44-9004-4a7f9e465a38/download/dados-socio-economicos-20112.csv
		 https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72/resource/488347cb-6d8d-4bda-8398-46c49f4b075d/download/dados-socioeconomicos-discentes-2020.2.csv

# Dados

In [52]:
df_datagov = pandas.DataFrame(resources)

In [53]:
df_datagov = df_datagov[sorted(df_datagov.keys())]

In [54]:
df_datagov.sample(3).T

,5,44,28
created,há mais de 4 anos,há mais de 4 anos,há 4 meses
criado,27/Outubro/2017,23/Novembro/2017,18/Agosto/2021
dataset_key,discentes,dados_socio_economicos_de_discentes,discentes
dataset_organization,Discentes,Dados Sócio-Econômicos de Discentes,Discentes
dataset_text,Relação dos discentes da UFRN.,Apresenta os dados sócio-econômicos dos discen...,Relação dos discentes da UFRN.
dataset_title,Discentes,Dados Sócio-Econômicos de Discentes,Discentes
dataset_url,"[/, /organization, /organization/universidade-...","[/, /organization, /organization/universidade-...","[/, /organization, /organization/universidade-..."
datastore_active,NaN,True,True
format,CSV,CSV,CSV
formato,CSV,CSV,CSV
havested,Thu Jan 13 18:09:19 2022,Thu Jan 13 18:09:40 2022,Thu Jan 13 18:09:30 2022
id,6c23a430-9a7c-4d0f-9602-1d5d97d40e6a,6a4c927a-150a-4630-b858-a32ec5c6495a,da0093b5-fd23-4ab4-8420-e73fc8962c24
last_modified,14 dias atrás,há 8 meses,22 dias atrás
licenca,Other (Open),Other (Open),Other (Open)
license_href,[http://opendefinition.org/okd/],[http://opendefinition.org/okd/],[http://opendefinition.org/okd/]
license_logo,[https://dados.gov.br/base/images/od_80x15_blu...,[https://dados.gov.br/base/images/od_80x15_blu...,[https://dados.gov.br/base/images/od_80x15_blu...
license_text,"[Licença, Other (Open)]","[Licença, Other (Open)]","[Licença, Other (Open)]"
license_title,[Este conjunto de dados satisfaz a Definição d...,[Este conjunto de dados satisfaz a Definição d...,[Este conjunto de dados satisfaz a Definição d...
package_id,554c2d41-cfce-4278-93c6-eb9aa49c5d16,8e0cb3ac-b6fa-48ef-a1ee-f2df0b893b72,554c2d41-cfce-4278-93c6-eb9aa49c5d16
position,5,9,28
resource_description,\n \n,\n \n,\n \n
resource_title,Ingressantes em 2014,Dados de Discentes em 2014.2,Ingressantes em 1999
resource_url,http://landpage-h.cgu.gov.br/dadosabertos/inde...,http://landpage-h.cgu.gov.br/dadosabertos/inde...,http://landpage-h.cgu.gov.br/dadosabertos/inde...
resource_url_out,https://dados.ufrn.br/dataset/554c2d41-cfce-42...,https://dados.ufrn.br/dataset/8e0cb3ac-b6fa-48...,https://dados.ufrn.br/dataset/554c2d41-cfce-42...
revision_id,ab707583-f565-4c17-a13e-a19619073ac0,aa9575b9-d8fc-4aa8-adef-88059844df0f,ab707583-f565-4c17-a13e-a19619073ac0
state,active,active,active
ultima_atualizacao,30/Dezembro/2021,9/Maio/2021,22/Dezembro/2021
webstore_last_updated,None,None,None
webstore_url,None,None,None

In [55]:
df_datagov.format.value_counts()

CSV    55
PDF     3
Name: format, dtype: int64

In [56]:
df_datagov.formato.value_counts()

CSV    55
PDF     3
Name: formato, dtype: int64

In [57]:
FN = lambda ext='json' : './dadosgov_{}_{}_query.{}'.format(alias,query.replace('+','_'), ext)
 
df_datagov.to_json(FN('json'))
df_datagov.to_csv(FN('csv'))
df_datagov.to_excel(FN('xls'))
for fn in ['json', 'csv', 'xls']:
    google.colab.files.download(FN(fn))

<ipython-input-57-cd87016e7687>:5: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  df_datagov.to_excel(FN('xls'))

ModuleNotFoundError: No module named 'xlwt'

# Leitura do banco de dados

In [58]:
df_discentes = df_datagov[df_datagov.dataset_key == 'discentes']
df_discentes = df_discentes[df_discentes.format == 'CSV']

In [59]:
DF_DISCENTES = []
for u,url in enumerate(df_discentes.resource_url_out.values):
    print(u,url)
    _dataframe = pandas.read_csv(url,encoding='UTF-8',sep=';')
    #_dataframe = pandas.read_csv(url,encoding='latin1',sep=';')
    DF_DISCENTES.append(_dataframe)

0 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/a55aef81-e094-4267-8643-f283524e3dd7/download/discentes-2019.csv
1 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/146b749b-b9d0-49b2-b114-ac6cc82a4051/download/discentes-2018.csv
2 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/dc732572-a51a-4d4a-a39d-2db37cbe5382/download/discentes-2017.csv
3 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/7d2fa5b3-743f-465f-8450-91719b34a002/download/discentes-2016.csv
4 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/e2b5b843-4f58-497e-8979-44daf8df8f94/download/discentes-2015.csv
5 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/6c23a430-9a7c-4d0f-9602-1d5d97d40e6a/download/discentes-2014.csv
6 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/dba208c2-822f-4e26-adc3-b61d4cb110b6/download/discentes-2013.csv
7 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/fc283aa9-61a7-4cf0-91fb-c403c0817b48/download/discentes-2012.csv
8 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/2bb3dec9-7f23-434c-a179-21515f91abc8/download/discentes-2011.csv
9 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/5fc61f78-19b4-4020-9f3c-c298cb8a63aa/download/discentes-2010.csv
10 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/861b96a8-5304-4e6a-a8c4-068533ec7cb9/download/discentes-2009.csv
11 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/7795c538-86fc-483f-9da9-67b2fcc834ae/download/discentes-2020.csv
12 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/ba2e0a43-305f-4020-b6a7-9c125f766f63/download/discentes-2008.csv
13 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/ed337a80-a0ba-4e69-b6f1-1493c51467ac/download/discentes-2002.csv
14 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/3cfa42b7-315f-4d02-abe7-fb81a495be5a/download/discentes-2007.csv
15 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/8bb0c8da-4221-4ade-abaa-2fe4b1f3502f/download/discentes-2006.csv
16 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/e3d118c9-73c8-47fe-8264-3f077a8ad44d/download/discentes-2005.csv
17 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/acdf58ab-c4fc-4199-a1a4-c58a39638ce7/download/discentes-2004.csv
18 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/3c9cbd05-8e20-4211-a068-423bd314572c/download/discentes-2001.csv
19 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/d6282624-a60b-4e97-af04-397f87c7a454/download/discentes-1998.csv
20 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/166d8d15-72a5-45cf-aeb6-795e7d2e14dc/download/discentes-1996.csv
21 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/018f6b0b-b788-4db0-99fc-0b0dc647d241/download/discentes-1995.csv
22 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/cf451687-b7a5-413a-b044-0c99ad9ee55e/download/discentes-1992.csv
23 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/ff37f985-cf9c-40f8-9ceb-201b22ebb8c6/download/discentes-1990.csv
24 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/db542795-74c8-4d92-8986-ccc331da6adb/download/discentes-1991.csv
25 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/ac2acdb3-02c0-4334-9865-d384eb2de3b6/download/discentes-2021.csv
26 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/e467b303-fa5a-4759-b6d9-0fef03df3d5a/download/discentes-2003.csv
27 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/da0093b5-fd23-4ab4-8420-e73fc8962c24/download/discentes-1999.csv
28 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/cb089e24-357e-49f9-8afd-18af5b3e2301/download/discentes-1997.csv
29 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/4a30217c-cc0f-4d0d-87c6-ee4a0aafd684/download/discentes-1994.csv
30 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/3e4a3eef-02e7-44c6-929e-5f4a3f795382/download/discentes-1993.csv
31 https://dados.ufrn.br/dataset/554c2d41-cfce-4278-93c6-eb9aa49c5d16/resource/2042b913-0ff8-4a3a-a7ca-c03a253a045e/download/discentes-2000.csv

In [60]:
DF_DISCENTES = pandas.concat(DF_DISCENTES)

In [81]:
NAME = []
for name in DF_DISCENTES[DF_DISCENTES.sexo == 'F']['nome_discente'].values:
    NAME.append(name.split()[0])

In [86]:
print(*sorted(set(filter(lambda x: re.findall('^U',x),set(NAME)))),sep='\n')

UAIANA
UBERLANDIA
UBERLANY
UBERLÂNDIA
UBIKARLA
UBIRACIRA
UBIRANDILMA
UBIRANEIDE
UBIRANILDA
UDICELI
UDIMARA
UEDINA
UELIANIA
UELIDA
UELMA
UENIA
UERLEIDE
UEZIA
UIACI
UIACY
UIARA
UIATANIRA
UIHARA
UILARA
UILIANE
UILIETE
UILLIANE
UILMA
UILSA
UIONARA
UIRANEIDE
UIRATÂNIA
ULANA
ULIANA
ULIANE
ULIANY
ULICÉLIA
ULISANDRA
ULISDETE
ULISMAR
ULISSEIA
ULLA
ULLI
ULLIKENIA
ULLY
ULRIKE
ULYANA
ULYSCLEY
ULYVÂNIA
UMARILANDIA
UMBELINA
UOTANA
URANEIDE
URANIA
URRACA
URSULA
UTA
UYARA
UZIELMA
UZINETE
UÉLIDA

In [123]:
DF_DISCENTES[DF_DISCENTES.nome_discente.transform(lambda nome: re.findall('^JOSÉ HENRIQUE',nome)!=[] )]

,matricula,nome_discente,sexo,ano_ingresso,periodo_ingresso,forma_ingresso,tipo_discente,status,sigla_nivel_ensino,nivel_ensino,id_curso,nome_curso,modalidade_educacao,id_unidade,nome_unidade,id_unidade_gestora,nome_unidade_gestora
7846,2.019302e+10,JOSÉ HENRIQUE MONTEIRO KREIMER FILHO,M,2019,1.0,PROCESSO SELETIVO,REGULAR,CANCELADO,T,TÉCNICO,4970.0,TÉCNICO DE MÚSICA (INSTRUMENTO),PRESENCIAL,284.0,ESCOLA DE MÚSICA,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
7847,2.019300e+10,JOSÉ HENRIQUE MOREIRA PINHEIRO,M,2019,1.0,PROCESSO SELETIVO,REGULAR,ATIVO,T,TÉCNICO,96054058.0,CURSO TÉCNICO DA METRÓPOLE DIGITAL,SEMI-PRESENCIAL,6069.0,INSTITUTO METROPOLE DIGITAL,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
10161,2.018203e+10,JOSÉ HENRIQUE BRANDINI NÉSPOLI,M,2018,2.0,PROCESSO SELETIVO,REGULAR,ATIVO,L,LATO SENSU,128492008.0,ESPECIALIZAÇÃO EM PRECEPTORIA EM SAÚDE,A DISTÂNCIA,205.0,ESCOLA DE SAÚDE,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
10162,2.018000e+10,JOSÉ HENRIQUE DE SOUZA MELO,M,2018,1.0,REOCUPAÇÃO DE VAGAS RESIDUAIS,REGULAR,ATIVO,G,GRADUAÇÃO,111635075.0,QUÍMICA,PRESENCIAL,439.0,CENTRO DE CIÊNCIAS EXATAS E DA TERRA,439.0,CENTRO DE CIÊNCIAS EXATAS E DA TERRA
10163,2.018302e+10,JOSÉ HENRIQUE MOREIRA DA COSTA,M,2018,1.0,PROCESSO SELETIVO,REGULAR,CONCLUÍDO,T,TÉCNICO,94763016.0,TÉCNICO EM AGENTE COMUNITÁRIO DE SAÚDE,PRESENCIAL,205.0,ESCOLA DE SAÚDE,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
10164,2.018006e+10,JOSÉ HENRIQUE TARGINO DIAS GÓIS,M,2018,1.0,SiSU,REGULAR,ATIVO,G,GRADUAÇÃO,92127264.0,TECNOLOGIA DA INFORMAÇÃO,PRESENCIAL,6069.0,INSTITUTO METROPOLE DIGITAL,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
11532,2.017200e+10,JOSÉ HENRIQUE DE SOUZA NETO,M,2017,1.0,PROCESSO SELETIVO,REGULAR,CANCELADO,L,LATO SENSU,117029625.0,"ESPECIALIZAÇÃO MBA EM CONTROLADORIA, FINANÇAS ...",PRESENCIAL,163.0,DEPARTAMENTO DE CIÊNCIAS CONTÁBEIS - DCC,443.0,CENTRO DE CIÊNCIAS SOCIAIS APLICADAS
9282,2.016101e+09,JOSÉ HENRIQUE TARGINO DIAS GÓIS,M,2016,1.0,SELEÇÃO DE PÓS-GRADUAÇÃO,REGULAR,CONCLUÍDO,D,DOUTORADO,17565631.0,DOUTORADO EM NEUROCIÊNCIAS,PRESENCIAL,5207.0,PROGRAMA DE PÓS-GRADUAÇÃO EM NEUROCIÊNCIAS,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
9851,2.015012e+10,JOSÉ HENRIQUE ALVES FERREIRA,M,2015,1.0,SiSU,REGULAR,CANCELADO,G,GRADUAÇÃO,111635050.0,FÍSICA,PRESENCIAL,439.0,CENTRO DE CIÊNCIAS EXATAS E DA TERRA,439.0,CENTRO DE CIÊNCIAS EXATAS E DA TERRA
9853,2.015201e+10,JOSÉ HENRIQUE VIEIRA DA CRUZ,M,2015,1.0,PROCESSO SELETIVO,REGULAR,CONCLUÍDO,L,LATO SENSU,106806058.0,ESPECIALIZAÇÃO EM GEOPROCESSAMENTO E CARTOGRAF...,PRESENCIAL,142.0,DEPARTAMENTO DE GEOGRAFIA/CCHLA,442.0,"CENTRO DE CIÊNCIAS HUMANAS, LETRAS E ARTES"
10519,2.014312e+09,JOSÉ HENRIQUE ALVES FERREIRA,M,2014,1.0,PROCESSO SELETIVO,REGULAR,CANCELADO,T,TÉCNICO,96054058.0,CURSO TÉCNICO DA METRÓPOLE DIGITAL,SEMI-PRESENCIAL,6069.0,INSTITUTO METROPOLE DIGITAL,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
8937,2.012944e+09,JOSÉ HENRIQUE LIMA DA SILVA,M,2012,1.0,VESTIBULAR,REGULAR,CONCLUÍDO,G,GRADUAÇÃO,2000039.0,FARMÁCIA,PRESENCIAL,441.0,CENTRO DE CIÊNCIAS DA SAÚDE,441.0,CENTRO DE CIÊNCIAS DA SAÚDE
8938,2.012042e+09,JOSÉ HENRIQUES TRIGUEIRO,M,2012,2.0,REINGRESSO AUTOMATICO,REGULAR,CONCLUÍDO,G,GRADUAÇÃO,2000046.0,HISTÓRIA,PRESENCIAL,442.0,"CENTRO DE CIÊNCIAS HUMANAS, LETRAS E ARTES",442.0,"CENTRO DE CIÊNCIAS HUMANAS, LETRAS E ARTES"
8939,2.012119e+09,JOSÉ HENRIQUE TARGINO DIAS GÓIS,M,2012,2.0,SELEÇÃO DE PÓS-GRADUAÇÃO,REGULAR,CONCLUÍDO,E,MESTRADO,17565630.0,MESTRADO EM NEUROCIÊNCIAS,PRESENCIAL,5207.0,PROGRAMA DE PÓS-GRADUAÇÃO EM NEUROCIÊNCIAS,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
7992,2.010083e+09,JOSÉ HENRIQUE SALLES PINHEIRO,M,2010,1.0,VESTIBULAR,REGULAR,CANCELADO,G,GRADUAÇÃO,2000144.0,QUÍMICA,A DISTÂNCIA,439.0,CENTRO DE CIÊNCIAS EXATAS E DA TERRA,439.0,CENTRO DE CIÊNCIAS EXATAS E DA TERRA
5360,2.009112e+09,JOSÉ HENRIQUE BENEDETTI PICCOLI FERREIRA,M,2009,1.0,ALUNO ESPECIAL POS-GRADUACAO,ESPECIAL,CANCELADO,E,MESTRADO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5361,2.009009e+09,JOSÉ HENRIQUE DE ARAÚJO,M,2009,1.0,VESTIBULAR,REGULAR,CANCELADO,G,GRADUAÇÃO,2000011.0,CIÊNCIAS CONTÁBEIS,PRESENCIAL,443.0,CENTRO DE CIÊNCIAS SOCIAIS APLICADAS,443.0,CENTRO DE CIÊNCIAS SOCIAIS APLICADAS
5362,2.009032e+09,JOSÉ HENRIQUE TARGINO DIAS GÓIS,M,2009,2.0,VESTIBULAR,REGULAR,CONCLUÍDO,G,GRADUAÇÃO,10320810.0,CIÊNCIAS E TECNOLOGIA,PRESENCIAL,4885.0,ESCOLA DE CIÊNCIAS E TECNOLOGIA,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
8498,2.020010e+10,JOSÉ HENRIQUE ANISIO LOURENÇO,M,2020,1.0,SiSU,REGULAR,ATIVO,G,GRADUAÇÃO,8068230.0,ENGENHARIA FLORESTAL,PRESENCIAL,351.0,ESCOLA AGRÍCOLA DE JUNDIAÍ,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
8501,2.020013e+10,JOSÉ HENRIQUE MONTEIRO KREIMER FILHO,M,2020,2.0,SiSU,REGULAR,TRANCADO,G,GRADUAÇÃO,10320810.0,CIÊNCIAS E TECNOLOGIA,PRESENCIAL,4885.0,ESCOLA DE CIÊNCIAS E TECNOLOGIA,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
8502,2.020300e+10,JOSÉ HENRIQUE MONTEIRO KREIMER FILHO,M,2020,1.0,PROCESSO SELETIVO,REGULAR,ATIVO,T,TÉCNICO,96054058.0,CURSO TÉCNICO DA METRÓPOLE DIGITAL,SEMI-PRESENCIAL,6069.0,INSTITUTO METROPOLE DIGITAL,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
8503,2.020009e+10,JOSÉ HENRIQUE VERÍSSIMO DANTAS XAVIER,M,2020,1.0,SiSU,REGULAR,ATIVO,G,GRADUAÇÃO,2000030.0,ENGENHARIA ELÉTRICA,PRESENCIAL,445.0,CENTRO DE TECNOLOGIA,445.0,CENTRO DE TECNOLOGIA
4106,2.008028e+09,JOSÉ HENRIQUE DE SOUZA MELO,M,2008,1.0,VESTIBULAR,REGULAR,CANCELADO,G,GRADUAÇÃO,111635075.0,QUÍMICA,PRESENCIAL,439.0,CENTRO DE CIÊNCIAS EXATAS E DA TERRA,439.0,CENTRO DE CIÊNCIAS EXATAS E DA TERRA
4107,2.008013e+09,JOSÉ HENRIQUES TRIGUEIRO,M,2008,1.0,VESTIBULAR,REGULAR,CONCLUÍDO,G,GRADUAÇÃO,111635057.0,HISTÓRIA,PRESENCIAL,442.0,"CENTRO DE CIÊNCIAS HUMANAS, LETRAS E ARTES",442.0,"CENTRO DE CIÊNCIAS HUMANAS, LETRAS E ARTES"
7578,2.021201e+10,JOSÉ HENRIQUE DE SOUZA NETO,M,2021,1.0,PROCESSO SELETIVO,REGULAR,CANCELADO,L,LATO SENSU,150765953.0,GESTÃO DINÂMICA DE PROJETOS,A DISTÂNCIA,161.0,DEPARTAMENTO DE CIÊNCIAS ADMINISTRATIVAS - DEPAD,443.0,CENTRO DE CIÊNCIAS SOCIAIS APLICADAS
7579,2.021002e+10,JOSÉ HENRIQUE MOREIRA DA COSTA,M,2021,2.0,SiSU,REGULAR,ATIVO,G,GRADUAÇÃO,10320810.0,CIÊNCIAS E TECNOLOGIA,PRESENCIAL,4885.0,ESCOLA DE CIÊNCIAS E TECNOLOGIA,605.0,UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE

In [130]:
import string

In [131]:
DF_DISCENTES.nome_discente.transform(lambda n: n.split())

0              [ABDENOR, BEZERRA, DOS, SANTOS]
1        [ABDIAS, MONTEIRO, DE, ANDRADE, MELO]
2           [ABDIAS, SABINO, RODRIGUES, FILHO]
3           [ABEL, GOMES, DE, OLIVEIRA, FILHO]
4            [ABI, AMANA, DE, AQUINO, BEZERRA]
                         ...
5301             [ZILENE, TAVARES, DE, CASTRO]
5302       [ZILKARLA, DOS, SANTOS, DE, ARAUJO]
5303      [ZOETE, FERREIRA, NEVES, DE, ARAUJO]
5304     [ZUILSON, AUGUSTO, CARLOS, DA, SILVA]
5305    [ZWINGLA, TEONIA, ALVES, DE, MEDEIROS]
Name: nome_discente, Length: 329376, dtype: object